# Generated by Django 2.2 on 2022-06-04 05:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('birthday', models.DateField(default=datetime.datetime(2022, 6, 4, 5, 50, 5, 390433, tzinfo=utc), verbose_name='Birthday')),
                ('street', models.CharField(max_length=200, verbose_name='Street')),
                ('city', models.CharField(max_length=200, verbose_name='City')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('zip_code', models.CharField(max_length=6, verbose_name='Zip Code')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='imgs/')),
            ],
        ),
    ]
