# Generated by Django 2.0 on 2022-06-12 00:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('start_date', models.DateField(default=datetime.datetime(2022, 6, 12, 0, 46, 13, 192994, tzinfo=utc), verbose_name='Start Date')),
                ('end_date', models.DateField(default=datetime.datetime(2022, 6, 12, 0, 46, 13, 192994, tzinfo=utc), verbose_name='End Date')),
            ],
        ),
    ]
