# Generated by Django 2.0 on 2022-06-14 17:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hr_jobs', '0001_initial'),
        ('hr_contracts', '0007_auto_20220615_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractmodel',
            name='job_id',
            field=models.ManyToManyField(to='hr_jobs.JobModel'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 14, 17, 58, 44, 509813, tzinfo=utc), verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 14, 17, 58, 44, 509813, tzinfo=utc), verbose_name='Start Date'),
        ),
    ]
